export const EVENT = {
  CONNECT: {
    ON: 'CONNECT_TO_SERVER',
    EMIT: 'CONNECT_FROM_SERVER',
  },
  NOTICE: {
    EMIT: 'NOTICE_FROM_SERVER',
  },
  GET_CHATROOMS: {
    ON: 'REQUEST_CHATROOMS_TO_SERVER',
    EMIT: 'GET_CHATROOMS_FROM_SERVER',
  },
  ENTER_ROOM_LIST: {
    ON: 'ENTERROOM_BY_LIST_TO_SERVER',
    // EMIT: 'ENTER_ROOM_FROM_SERVER', 입장 시 채팅을 RETURN 하기에 GET_CHATS.EMIT을 사용한다
  },
  ENTER_ROOM_DM: {
    ON: 'ENTERROOM_BY_DM_TO_SERVER',
    // EMIT: 'ENTER_ROOM_FROM_SERVER', 입장 시 채팅을 RETURN 하기에 GET_CHATS.EMIT을 사용한다
  },
  LEAVE_ROOM: {
    ON: 'LEAVE_ROOM_TO_SERVER',
    EMIT: 'LEAVE_ROOM_FROM_SERVER',
  },
  EXIT_ROOM: {
    ON: 'EXIT_ROOM_TO_SERVER',
    EMIT: 'EXIT_ROOM_FROM_SERVER',
  },
  GET_CHATS: {
    ON: 'REQUEST_CHATS_TO_SERVER',
    EMIT: 'GET_CHATS_FROM_SERVER',
  },
  SEND_CHAT: {
    ON: 'SEND_CHAT_TO_SERVER',
    EMIT: 'GET_CHAT_FROM_SERVER',
  },
  DELETE_CHAT: {
    ON: 'DELETE_CHAT_TO_SERVER',
    EMIT: 'DELETE_CHAT_FROM_SERVER',
  },
};
